name: feedback_system
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  cupertino_icons: ^0.1.2
  flutter_spinkit: "^4.1.1"
  fluttertoast: ^3.1.3
  awesome_dialog:
  grouped_buttons: ^1.0.3
  progress_dialog: ^1.2.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true