name: feedback_system
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  cupertino_icons: ^0.1.2
  flutter_spinkit: "^4.1.1"
  fluttertoast: ^3.1.3
  awesome_dialog:
  progress_dialog: ^1.2.1
  qr_flutter: ^3.1.0
  path_provider: 0.4.1
  image_gallery_saver: ^1.2.2
  permission_handler:
  flutter_share_file:
  image_picker_saver: ^0.3.0
  share_extend: ^1.1.2
  shared_preferences: ^0.5.6+3
  qr_code_scanner: 0.0.12
  material_design_icons_flutter: 4.0.5045
  flutter_speed_dial: ^1.2.5
  flare_splash_screen: ^3.0.1
  flutter_fluid_slider: ^1.0.2
  grouped_buttons: ^1.0.4
  reviews_slider: "^1.0.4"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

module:
  androidX: true